config/routes.rb
Calc::Application.routes.draw do
  get "mortgage_calc/details"

  get "mortgage_calc/results"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mortgage_calc_controller.rb
class MortgageCalcController < ApplicationController

  def details
  end

  def results
    @loan_amount = params[:loan_amount]
    @term_length = params[:term_length]
    @interest_rate = params[:interest_rate]
    raise "Loan amount must have a value" unless @loan_amount
    @monthly_payment = calculate_monthly_payment(@loan_amount.to_f, @term_length.to_f, @interest_rate.to_f)
  end

  # The formula for calculating a fixed monthly payment for a loan is:
  #     P = L[c(1 + c)^n]/[(1 + c)^n - 1]
  #
  # where
  #  L is the Loan Amount
  #  c is the monthly interest rate (divide by 12)
  #  n is the number of months
  #
  # params given:
  #  loan_amount
  #  term_length is term length in years
  #  annual_interest_rate_perc is annual interest rate as a percentage
  def calculate_monthly_payment(loan_amount, term_length, annual_interest_rate_perc)
    number_of_months = term_length * 12
    monthly_interest_rate = annual_interest_rate_perc / 100 / 12
    one_plus_c_to_n = (1 + monthly_interest_rate) ** number_of_months
    (loan_amount * (monthly_interest_rate * one_plus_c_to_n) / (one_plus_c_to_n - 1)).round(2)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mortgage_calc_helper.rb
module MortgageCalcHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calc</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mortgage_calc/details.html.erb
<h1>Mortgage Calculator Details</h1>

<p>Calculates how much you pay on your mortgage per month for a fixed rate.</p>


<%= form_tag("/mortgage_calc/results", method: "get") do %>
  <ul>
    <li>
      <%= label_tag(:loan_amount, "Loan Amount:") %>
      <%= text_field_tag(:loan_amount) %>
    </li>

    <li>
      <%= label_tag(:term_length, "Term Length (years):") %>
      <%= text_field_tag(:term_length) %>
    </li>

    <li>
      <%= label_tag(:interest_rate, "Interest Rate:") %>
      <%= text_field_tag(:interest_rate) %>
    </li>

  </ul>

  <%= submit_tag("Calculate") %>

<% end %>

app/views/mortgage_calc/results.html.erb
<h1>Mortgage Calculator Results</h1>

<p>Monthly Payment Amount</p>

<table>
  <tr>
    <td>Loan Amount</td><td><%= @loan_amount %></td>
  </tr>
  <tr>
    <td>Term Length (years)</td><td><%= @term_length %></td>
  </tr>
  <tr>
    <td>Interest Rate</td><td><%= @interest_rate %></td>
  </tr>
  <tr>
    <td><b>Monthly Payment</b></td><td><b><%= @monthly_payment %></b></td>
  </tr>
</table>

<%= link_to "Re enter", mortgage_calc_details_path %>